version: '3.9'
services:
  db:
    image: mongo:latest
    volumes:
      - db-data:/var/lib/mongo/data
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: unless-stopped

  app:
    build: ./
    depends_on:
      - db
    volumes:
      - app-data:/var/lib/app/data
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - DATABASE_NAME=courses
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
    restart: unless-stopped

volumes:
  db-data:
  app-data:
