name: ci
on: [push, pull_request]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install & Build
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Unit tests
        run: npm run test:ci
        working-directory: ${{env.working-directory}}
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: verify
        run: mvn -B verify